### ISSUE TITLE
upsscp.py throws exception on N-SET

### ISSUE THREAD

**Issue by christof-schadt-bl** [sjswerdloff/tdwii_plus_examples#76] opened 2024-10-10 10:33 UTC
Setup
Python tool based on pynetdicom issuing a send_n_set() command.

Observed behavior
After sending the n_set command, in upscp.py the handle_nset handler is properly called. But then internally, in handlers.py, line 646, search() throws an exception with the statement: AttributeError("The corresponding event is not a C-FIND, C-GET or C-MOVE request and has no 'Identifier' parameter").
Due due to error message, it is not fully clear, whether this is an internal issue, or whether something provided in the N-SET command has an issue.

**Comment by sjswerdloff** [comment] 2024-10-11 23:59
Please paste in screen content/log from upsscp.py --debug
Ideally from the start of the specific association for the N-SET-RQ.

The message listed is not present in the main branch, but might be in commits earlier than July 2024.

The message can be found in pynetdicom when accessing event.identifier
event.identifer is still being accessed in upsscp.py for N-GET and C-FIND (N-GET is optional in TDW-II, and that hasn't been tested... a brief code inspection indicates it would fail and give that message, so I'll add a separate issue for "support N-GET")

I haven't been bumping the version (semantic versioning) on each commit, so I'll start doing so to help in tracking.

**Comment by sjswerdloff** [comment] 2024-10-12 05:40
PR #61 Seems to be where the major change happened that switched from trying to use "event.identifier" to the decoded dataset in the N-SET-RQ.

**Comment by sjswerdloff** [comment] 2024-10-16 20:00
This was fixed in #61 
confirmed with @christof-schadt-bl that after synchronising his social fork and fetch/pull main that this issue went away

**Closed by sjswerdloff** 2024-10-16 20:00 UTC
Labels: bug
